### ISSUE TITLE
Registration Activation

### ISSUE THREAD

**Issue by mikebattye** [asimshah/booking-app#49] opened 2017-03-24 12:10 UTC
I registered a new member (Chris Rowlands) but the Activation email did not show in Mail History. I had to resend the email via the Membership app. This appeared OK in Mail History and the activation link worked to complete the registration.

**Comment by asimshah** [comment] 2017-03-25 13:16
This looks like an intermittent problem - I tried a couple of registrations here and one generated the activation email but the other did not.
Looking more closely, I have a theory for why this might happen but it requires a particular combination of events in time a sequence which is hard to produce manually.
So I have changed the way emails are sent by the webframe system (as opposed to the booking app) so that this problem will not occur (if my theory is correct). It will however require confirming that all emails do still work (i.e. registration, password reset, email address change as well as the various booking app emails).
This change will be in the next version.

**Comment by asimshah** [comment] 2017-03-25 13:18
Manual resend of any emails should also be confirmed as still working.

**Comment by asimshah** [comment] 2017-03-25 14:00
The test site is now upgraded for this fix.

**Comment by mikebattye** [comment] 2017-03-25 19:17
Remind me that this is important when you upgrade.

**Comment by asimshah** [comment] 2017-03-26 22:52
If you read my comments, you will see that I had already upgraded the site. The whole point of generating these issues are that they are the reminders. They should only be closed when there is nothing left to do in connection with them.
(I can see that you simply replied to the generated email - the trouble with that is you do not notice that further comments may have been added - a better idea is to use the link at the bottom of the email : "View it on Github")

**Comment by mikebattye** [comment] 2017-03-28 10:23
OK. I understand that now.



Regards, Mike

Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by mikebattye** [comment] 2017-03-30 10:37
Logged into CMS today (30Mar 11:30) but I can't see any emails sent after 26Mar2017 23:15:03.

**Comment by mikebattye** [comment] 2017-03-30 10:52
Further to this: the email cycle appears to be working for bookings (I did a complete test for a new booking Mar17/005). It is just the registration activation email that is missing again (Carmel Gray: G219646).

**Comment by asimshah** [comment] 2017-03-30 12:42
There continues to be some sort of intermittent problem. I tried many registrations on my development system and all but one generated a record in the mail history for account activation. Interestingly, the very first one failed and all subsequent ones worked.
My theory for why it was not working may well be wrong ...
I have added some further tracing to the log file in the hope that it will occur again and I'll be able to track it down.
This will be in the next version. Once it is available to you please try new registrations and see if you can get some to work. Please also record as much info as possible and see if some pattern is discernible.

**Comment by asimshah** [comment] 2017-03-30 12:53
I have upgraded the test site.

**Comment by mikebattye** [comment] 2017-03-30 13:02
Registered Martyn Joynes at 14:00 today on upgraded site. This worked.

**Comment by mikebattye** [comment] 2017-03-30 13:07
And another successfully at 14:06.

**Comment by mikebattye** [comment] 2017-03-30 13:15
The resend activation email worked for Carmel Gray. Her membership is now confirmed. All her details were correct the only problem I can see is that the original activation email was not sent. Unfortunately(?) can't seem to reproduce this after the upgrade.

**Comment by asimshah** [comment] 2017-03-31 14:47
Yet another fix - will be in the next version

**Closed** 2017-04-07 09:03 UTC
